# Generated by Django 3.2 on 2021-07-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
