# Generated by Django 3.2 on 2021-07-19 04:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0003_chatlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='chatroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mychat.chatroom'),
            preserve_default=False,
        ),
    ]
