# Generated by Django 3.2 on 2021-07-20 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0004_chatlog_chatroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatlog',
            old_name='user',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='chatroom',
        ),
    ]
