# Generated by Django 3.2 on 2021-07-20 04:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0005_auto_20210720_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatlog',
            old_name='name',
            new_name='user',
        ),
        migrations.AddField(
            model_name='chatlog',
            name='chatroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mychat.chatroom'),
            preserve_default=False,
        ),
    ]
